---
- name: check whether the port {{ port }} is used
  wait_for:
    port: "{{ port }}"
    state: stopped
    timeout: 1
    msg: "port {{ port }} is already used"

- name: echo install_path
  debug:
    msg: "install_path: {{ install_path }}"

- name: check whether the mysql basedir exist
  wait_for:
    path: "{{ basedir }}"
    state: absent
    timeout: 1
    msg: "mysql basedir {{ basedir }} is alreday exist"

- name: check whether the MYSQL_HOME env exist
  wait_for:
    path: "~/.bash_profile"
    search_regex: "MYSQL_HOME"
    timeout: 1
  register: env_exist
  failed_when: env_exist.elapsed == 0
