---
- name: mysql initialize
  shell: ./mysqld --user={{ user }} --initialize-insecure
  args:
    chdir: "{{ basedir }}/bin"

- name: mysql start
  shell: ./mysqld_safe --defaults-file="{{ basedir}}/my.cnf" --user={{ user }} &
  args:
    chdir: "{{ basedir }}/bin"
