---
- name: get tar from master
  copy:
    src: /etc/ansible/roles/java/files/jdk1.8.zip
    dest: /usr/lib/jvm/
    force: no

- name: unzip jdk 1.8
  unarchive:
    src: /usr/lib/jvm/jdk1.8.zip
    dest: /usr/lib/jvm

- name: remove zip file
  file: 
    path: /usr/lib/jvm/jdk1.8.zip
    state: absent 
