---
- name: 设置 JAVA_HOME 环境变量
  blockinfile:
    path: "~/.bash_profile"
    block: |

      # Set JAVA_HOME environment variable
      export JAVA_HOME={{ java_home }}
      export PATH=$PATH:$JAVA_HOME/bin
    marker: "# {mark} JAVA_HOME environment variable BLOCK"