---
# mysql版本
mysql_version: "5.7.41"       

# mysql端口
mysql_port: "3308"            

# mysql密码
mysql_pass: "3141"            

# mysql二进制包的下载地址
download_url: "http://192.168.123.222/mysql/{{ tarball }}"  

# mysql安装路径,默认为ansible用户的家目录
install_path: "{{ ansible_env.HOME }}"

# 软链接，指向"{{ install_path }}/{{ extractdir }}"，方便切换mysql版本，默认为{{ install_path }}下的mysql
basedir: "{{ install_path }}/mysql"    

# mysql数据存放的路径，默认{{ install_path }}下的data目录
datadir: "{{ install_path }}/data"     

# mysql运行的用户
user: "{{ ansible_ssh_user }}"         

# mysql运行的用户组
group: "{{ ansible_ssh_user }}"       

# innodb缓存池大小，默认使用主机的内存大小的50%
innodb_buffer_pool_size: "{{ (ansible_memtotal_mb * 0.5) | int }}M" 

# innodb日志文件大小，默认使用主机的内存大小的10%
innodb_log_file_size: "{{ (ansible_memtotal_mb * 0.1) | int }}M"    

# mysql服务的id号，默认使用ansible默认IP地址的第四个数字作为id号
server_id: "{{ ansible_default_ipv4.address.split('.')[3] }}"       

# mysql二进制包的名称【不要修改】
tarball: "mysql-{{ mysql_version }}-linux-glibc2.12-x86_64.tar.gz"  

# mysql二进制包解压后的目录名称【不要修改】
extractdir: "mysql-{{ mysql_version }}-linux-glibc2.12-x86_64"